Algoritmo "EX-A-66-QUADRADO"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Quadrado dos números inteiros de 15 a 200
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 16/04/2024
Var
contadora,resultado:inteiro

Inicio
   para contadora de 15 ate 200 passo 1 faca
      resultado <- contadora * contadora
      escreval(contadora, " ^ 2 =", resultado)
   fimpara
Fimalgoritmo