Algoritmo "EX-F-5_6_1-DIVISIVEIS-POR-4"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os valores divisíveis por 4 até 200
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 16/04/2024
Var
   contadora:inteiro

Inicio
   para contadora de 1 ate 200 passo 1 faca
      se contadora % 4 = 0 entao
         escreval (contadora)
      fimse
   fimpara
Fimalgoritmo