Algoritmo "EX-B-5_1_1-CONTAR-ATE-100"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : conta ate 100
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 30/03/2024
Var

   contador, soma: inteiro

Inicio
   contador <- 1
   soma <- 0

   Enquanto contador <= 100 faca
      soma <- soma + contador
      contador <- contador + 1
   FimEnquanto
   Escreva(soma)
Fimalgoritmo