Algoritmo "EX-A-07-CELSIUS-PARA-FAHRENHEIT"
// Disciplina   : [Logica de programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula o celsius para fahrenheit
// Autor(a)    : Gabriel Do Amaral Alves
// Data atual  : 17/03/2024
Var
celsius, calculo:real
Inicio
Escreva("Digite a temperatura em Celsius (°C):")
leia(celsius)
calculo <- (9 * celsius + 160) / 5
Escreval("A sua temperatura em Fahrenheit fica:",calculo,"°F")
Fimalgoritmo