Algoritmo "EX-B-07-FAHRENHEIT-PARA-CELSIUS"
// Disciplina   : [Logica de programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula fahrenheit para celsius
// Autor(a)    : Gabriel Do Amaral Alves
// Data atual  : 17/03/2024
Var
fahrenheit, calculo:real
Inicio
Escreval("Digite a temperatura em Fahrenheit (ºF): ")
leia(fahrenheit)
calculo <- (fahrenheit - 32) * (5/9)
Escreval("A sua temperatura em Celsius fica: ",calculo:2:2,"ºC")

Fimalgoritmo