Algoritmo "EX-A-APRESENTAR-OS-QUADRADOS-DO-NUMERO-INTEIRO"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 03/04/2024
Var

   numero:inteiro

Inicio

     numero <- 15
   repita
      Escreval(numero * numero)
      numero <- numero + 1
   ate numero > 200

Fimalgoritmo